[project]
name = "comfyui-selector"
description = "𝌸 EXDYSA. Selector and Recourse. Presets & failsafes. Work flow."
version = "2.0.1"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/exdysa/comfyui-selector"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "exdysa"
DisplayName = "comfyui-selector"
Icon = ""
