[project]
name = "comfyui-selector"
description = "𝌸 EXDYSA. Selector. Recourse. Fork. Unite. Presets & failsafes. Work flow."
version = "3.0.0"
license = "LICENSE"

[project.urls]
Repository = "https://github.com/exdysa/comfyui-selector"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "exdysa"
DisplayName = "comfyui-selector"
Icon = ""
